version: '3.8'

services:
     admin-2710:
        build:
          context: admin-2.7.10
          dockerfile: Dockerfile
        ports:
            - "9910:9910"
        environment:
            - SERVER_PORT=9910
            - SECURITY_BASIC_ENABLED=false
            - MANAGEMENT_SECURITY_ENABLED=false
     admin-2711:
        build:
          context: admin-2.7.11
          dockerfile: Dockerfile
        ports:
            - "9911:9911"
        environment:
            - SERVER_PORT=9911
            - SECURITY_BASIC_ENABLED=false
            - MANAGEMENT_SECURITY_ENABLED=false

     client-2711:
        build:
          context: client-2.7.11
          dockerfile: Dockerfile
        ports:
            - "9811:9811"
        environment:
            - SERVER_PORT=9811
            - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin-2711:9911, http://admin-2710:9910
            - spring.boot.admin.client.register-once=false
            - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL=http://client-2711:9811
            - SECURITY_BASIC_ENABLED=false
            - MANAGEMENT_SECURITY_ENABLED=false

     client-2710:
        build:
          context: client-2.7.10
          dockerfile: Dockerfile
        ports:
            - "9810:9810"
        environment:
            - SERVER_PORT=9810
            - SPRING_BOOT_ADMIN_CLIENT_URL=http://admin-2711:9911,http://admin-2710:9910
            - spring.boot.admin.client.register-once=false
            - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL=http://client-2710:9810
            - SECURITY_BASIC_ENABLED=false
            - MANAGEMENT_SECURITY_ENABLED=false